
//All domination voice lines from Sniper

//Scout
#define SNIPER_DOMINATE_SCOUT01 "vo/sniper_dominationscout01.mp3"
#define SNIPER_DOMINATE_SCOUT02 "vo/sniper_dominationscout02.mp3"
#define SNIPER_DOMINATE_SCOUT03 "vo/sniper_dominationscout03.mp3"
#define SNIPER_DOMINATE_SCOUT04 "vo/sniper_dominationscout04.mp3"
#define SNIPER_DOMINATE_SCOUT05 "vo/sniper_dominationscout05.mp3"
#define SNIPER_DOMINATE_SCOUT06 "vo/sniper_dominationscout06.mp3"
#define SNIPER_DOMINATE_SCOUT07 "vo/sniper_dominationscout07.mp3"

//Soldier
#define SNIPER_DOMINATE_SOLDIER01 "vo/sniper_dominationsoldier01.mp3"
#define SNIPER_DOMINATE_SOLDIER02 "vo/sniper_dominationsoldier02.mp3"
#define SNIPER_DOMINATE_SOLDIER03 "vo/sniper_dominationsoldier03.mp3"
#define SNIPER_DOMINATE_SOLDIER04 "vo/sniper_dominationsoldier04.mp3"
#define SNIPER_DOMINATE_SOLDIER05 "vo/sniper_dominationsoldier05.mp3"
#define SNIPER_DOMINATE_SOLDIER06 "vo/sniper_dominationsoldier06.mp3"
#define SNIPER_DOMINATE_SOLDIER07 "vo/sniper_dominationsoldier07.mp3"

//Pyro
#define SNIPER_DOMINATE_PYRO01 "vo/sniper_dominationpyro01.mp3"
#define SNIPER_DOMINATE_PYRO02 "vo/sniper_dominationpyro02.mp3"
#define SNIPER_DOMINATE_PYRO03 "vo/sniper_dominationpyro03.mp3"
#define SNIPER_DOMINATE_PYRO04 "vo/sniper_dominationpyro04.mp3"
#define SNIPER_DOMINATE_PYRO05 "vo/sniper_dominationpyro05.mp3"
#define SNIPER_DOMINATE_PYRO06 "vo/sniper_dominationpyro06.mp3"
#define SNIPER_DOMINATE_PYRO07 "vo/sniper_dominationpyro07.mp3"

//Demoman
#define SNIPER_DOMINATE_DEMOMAN01 "vo/sniper_dominationdemoman01.mp3"
#define SNIPER_DOMINATE_DEMOMAN02 "vo/sniper_dominationdemoman02.mp3"
#define SNIPER_DOMINATE_DEMOMAN03 "vo/sniper_dominationdemoman03.mp3"
#define SNIPER_DOMINATE_DEMOMAN04 "vo/sniper_dominationdemoman04.mp3"
#define SNIPER_DOMINATE_DEMOMAN05 "vo/sniper_dominationdemoman05.mp3"
#define SNIPER_DOMINATE_DEMOMAN06 "vo/sniper_dominationdemoman06.mp3"
#define SNIPER_DOMINATE_DEMOMAN07 "vo/sniper_dominationdemoman07.mp3"

//Heavy
#define SNIPER_DOMINATE_HEAVY01 "vo/sniper_dominationheavy01.mp3"
#define SNIPER_DOMINATE_HEAVY02 "vo/sniper_dominationheavy02.mp3"
#define SNIPER_DOMINATE_HEAVY03 "vo/sniper_dominationheavy03.mp3"
#define SNIPER_DOMINATE_HEAVY04 "vo/sniper_dominationheavy04.mp3"
#define SNIPER_DOMINATE_HEAVY05 "vo/sniper_dominationheavy05.mp3"
#define SNIPER_DOMINATE_HEAVY06 "vo/sniper_dominationheavy06.mp3"
#define SNIPER_DOMINATE_HEAVY07 "vo/sniper_dominationheavy07.mp3"

//Engineer
#define SNIPER_DOMINATE_ENGI01 "vo/sniper_dominationengineer01.mp3"
#define SNIPER_DOMINATE_ENGI02 "vo/sniper_dominationengineer02.mp3"
#define SNIPER_DOMINATE_ENGI03 "vo/sniper_dominationengineer03.mp3"
#define SNIPER_DOMINATE_ENGI04 "vo/sniper_dominationengineer04.mp3"
#define SNIPER_DOMINATE_ENGI05 "vo/sniper_dominationengineer05.mp3"
#define SNIPER_DOMINATE_ENGI06 "vo/sniper_dominationengineer06.mp3"
#define SNIPER_DOMINATE_ENGI07 "vo/sniper_dominationengineer07.mp3"

//Medic
#define SNIPER_DOMINATE_MEDIC01 "vo/sniper_dominationmedic01.mp3"
#define SNIPER_DOMINATE_MEDIC02 "vo/sniper_dominationmedic02.mp3"
#define SNIPER_DOMINATE_MEDIC03 "vo/sniper_dominationmedic03.mp3"
#define SNIPER_DOMINATE_MEDIC04 "vo/sniper_dominationmedic04.mp3"
#define SNIPER_DOMINATE_MEDIC05 "vo/sniper_dominationmedic05.mp3"
#define SNIPER_DOMINATE_MEDIC06 "vo/sniper_dominationmedic06.mp3"
#define SNIPER_DOMINATE_MEDIC07 "vo/sniper_dominationmedic07.mp3"

//Sniper
#define SNIPER_DOMINATE_SNIPER01 "vo/sniper_dominationsniper01.mp3"
#define SNIPER_DOMINATE_SNIPER02 "vo/sniper_dominationsniper02.mp3"
#define SNIPER_DOMINATE_SNIPER03 "vo/sniper_dominationsniper03.mp3"
#define SNIPER_DOMINATE_SNIPER04 "vo/sniper_dominationsniper04.mp3"
#define SNIPER_DOMINATE_SNIPER05 "vo/sniper_dominationsniper05.mp3"
#define SNIPER_DOMINATE_SNIPER06 "vo/sniper_dominationsniper06.mp3"
#define SNIPER_DOMINATE_SNIPER07 "vo/sniper_dominationsniper07.mp3"

//Spy
#define SNIPER_DOMINATE_SPY01 "vo/sniper_dominationspy01.mp3"
#define SNIPER_DOMINATE_SPY02 "vo/sniper_dominationspy02.mp3"
#define SNIPER_DOMINATE_SPY03 "vo/sniper_dominationspy03.mp3"
#define SNIPER_DOMINATE_SPY04 "vo/sniper_dominationspy04.mp3"
#define SNIPER_DOMINATE_SPY05 "vo/sniper_dominationspy05.mp3"
#define SNIPER_DOMINATE_SPY06 "vo/sniper_dominationspy06.mp3"
#define SNIPER_DOMINATE_SPY07 "vo/sniper_dominationspy07.mp3"
